name: Lighthouse CI Demo

on: push

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://hash.green/
            https://hash.green/dex
            https://hash.green/dex/XCH-USDS
          uploadArtifacts: true
