name: Lighthouse CI Demo

on: push

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://hash.green/
            https://hash.green/dex/XCH-USDS
          # uploadArtifacts: true
          serverBaseUrl: ${{ secrets.LHCI_SERVER_URL }}
          serverToken: ${{ secrets.LHCI_SERVER_TOKEN }}
          # temporaryPublicStorage: true
          # configPath: './lighthouserc.json'
